name: kaggle

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - jupyterlab
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - tqdm
  - pip
